### ISSUE TITLE
multi clips

### ISSUE THREAD

**Issue by gaborgabor** [dag0310/clippy#1]
Hi,
This is wonderful but I am not sure how could I use this single clipboard?
Would this be possible to have many clipboards (per sub-folders or somehow)? 
Thanks

**Comment by dag0310** [comment]
This is already possible, although it's more or less a hidden feature since it is not at all intuitive: If you enter any text inside the header (which is actually just the placeholder "Clippy" inside an input field) a new text file (clipboard) will be created on the server as soon as you start typing something in the text area below. So just by changing the header title you can switch between clipboards (avoid spaces and special characters). If you press ENTER in the header field you can even make it password protected.
